import type { Metadata } from "next";
import { inter } from "@/app/[locale]/ui/fonts";
import "./globals.css";

export async function generateMetadata() {
  // const { locale } = await params;
  // console.log(locale);
  return {
    title: "Create Next App",
    description: "Generated by create next app",
    icon: "my-icon.ico",
  };
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className="dark">
      <body
        className={`${inter.className} antialiased text-foreground bg-background`}
      >
        {children}
      </body>
    </html>
  );
}
