export default {
  common: {
    account_creation: "Account creation",
    already_account: "Already have an account ?",
    cancel: "Cancel",
    capital_and: "AND",
    capital_or: "OR",
    connect: "Connect",
    connection: "Connection",
    connection_google: "Connect with Google",
    create_account: "Create an account",
    dark_mode: "Dark mode",
    email: "E-mail",
    first_name: "First name",
    forgot_password: "Forget password ?",
    image: "Image",
    lang_change_en: "Version française",
    lang_change_fr: "English version",
    logout: "Logout",
    max: "Max",
    min: "Min",
    name: "Name",
    password: "Password",
    settings: "Settings",
    stats: "Stats",
    validate: "Validate",
  },
  character: {
    single: "Character",
    absence_threshold: "Absence threshold",
    age: "Age",
    change_character: "Change character",
    create: "New character",
    create_link: "Create a new character",
    composure: "Composure",
    exhaustion_threshold: "Exhaustion threshold",
    fault: "Fault",
    fitness: "Fitness",
    header_base: "Base",
    header_name: "Name",
    header_points: "Points distributed",
    header_total: "Total",
    job: "Job",
    jobGroup: "Job group",
    level: "Level",
    life: "Health",
    magic: "Magic",
    mana: "Mana",
    max_fitness: "Max fitness",
    max_fitness_tooltip:
      "The maximum amount of fitness your character has (strength + agility).\nThe fitness allow the use of fitness techniques.",
    max_health: "Max health",
    max_health_tooltip:
      "The maximum amount of health your character has (constitution x 2).",
    max_mana: "Max mana",
    max_mana_tooltip:
      "The maximum amount of mana your character has (intelligence + power).\nThe fitness allow the cast of spells.",
    modify: "Modify Character",
    nationality: "Nationality",
    no_character: "No character found",
    quality: "Quality",
    relations_close: "Close",
    relations_distant: "Distant",
    relations_enemy: "Enemy",
    relations_opposite: "Opposite",
    religion: "Religion",
    research_placeholder: "Search by name",
    sex: "Sex",
    wound_threshold: "Wound threshold",
  },
  guild: {
    single: "Guild",
  },
  inventory: {
    single: "Inventory",
  },
  market: {
    single: "Market",
  },
  pet: {
    single: "Pet & mount",
  },
  race: {
    single: "Race",
    add: "Add a new race",
    appearance: "Appearence",
    blood_cross: "Crossbred",
    blood_half: "Half-blood",
    blood_percentage: "Blood Percentage",
    blood_pure: "Pure-blood",
    breading_race: "Breading race",
    categorie: "Categorie",
    character: "Character",
    create: "New race",
    playable: "Playable",
    plural: "Races",
    primary_race: "Primary race",
    race_placeholder: "Choose a race",
    stat1: "Stat 1",
    stat2: "Stat 2",
    type: "Type",
    type_placeholder: "Choose a blood familly",
  },
  relation: {
    plural: "Relations",
  },
  stat: {
    agility: "Agility",
    agility_tooltip:
      "Determine the agilitty level of your character\nand increase their max fitness",
    constitution: "Constitution",
    constitution_tooltip:
      "Determine the constitution level of yout character\nand incease their max health",
    force: "Strength",
    force_tooltip:
      "Determine the strength level of your character\nand increase their max fitness",
    intelligence: "Intelligence",
    intelligence_tooltip:
      "Determine the intelligence level of your character\nand your max mana.\nInfluances your character's knowledge.",
    knowHow: "Knowhow",
    knowHow_tooltip: "Determine the know-how level of your character.",
    power: "Power",
    power_tooltip:
      "Determine the power level of your character\nand your max mana.\nInfluances your character's magical capacity.",
    sociable: "Sociable",
    sociable_tooltip:
      "Determine the sociable level of your character.Influences the image your character conveys to others.",
    social: "Social",
    social_tooltip:
      "Determine the social level of your character.\nInfluances your character's capacity to influence others.",
    to_allocate: "Points to allocate",
    too_much_max: "too much stats at maximum points ({maxPoints})",
    will: "Will",
    will_tooltip:
      "Determine the will level of your character.\nInfluances your character's perception.",
  },
  technique_spell: {
    plural: "Spells & Techniques",
    active: "Active",
    passive: "Passive",
  },
} as const;
