export default {
  common: {
    account_creation: "Création de compte",
    already_account: "Déja un compte ?",
    cancel: "Annuler",
    capital_and: "ET",
    capital_or: "OU",
    connect: "Se connecter",
    connection: "Connexion",
    connection_google: "Connexion avec Google",
    create_account: "Créer un compte",
    dark_mode: "Mode sombre",
    email: "E-mail",
    first_name: "Prénom",
    forgot_password: "Mot de passe oublié ?",
    image: "Image",
    lang_change_en: "Version française",
    lang_change_fr: "English version",
    logout: "Se déconnecter",
    max: "Max",
    min: "Min",
    name: "Nom",
    password: "Mot de passe",
    settings: "Paramètres",
    stats: "Stats",
    validate: "Valider",
  },
  character: {
    single: "Personnage",
    absence_threshold: "Seuil d'absence",
    age: "Age",
    change_character: "Changer de personnage",
    create: "Nouveau personnage",
    create_link: "Créer un nouveau personnage",
    composure: "Sang-froid",
    exhaustion_threshold: "Seuil de fatigue",
    fault: "Défaut",
    fitness: "Forme",
    header_base: "Base",
    header_name: "Nom",
    header_points: "Points répartis",
    header_total: "Totale",
    job: "Métier",
    jobGroup: "Groupe de métier",
    level: "Niveau",
    life: "Santé",
    magic: "Magie",
    mana: "Mana",
    max_fitness: "Forme max",
    max_fitness_tooltip:
      "La quantité maximale de forme de votre personnage (force + agilité).\nLa forme permet d'utiliser des techniques de formes.",
    max_health: "Santé max",
    max_health_tooltip:
      "La quantité maximale de points de vie de votre personnage (consitution x 2).",
    max_mana: "Mana max",
    max_mana_tooltip:
      "La quantité maximale de mana de votre personnage (intelligence + pouvoir).\nLe mana permet de lancer des sorts.",
    modify: "Modification du Personnage",
    nationality: "Nationnalité",
    no_character: "Pas de personnage trouvé",
    quality: "Qualité",
    relations_close: "Proche",
    relations_distant: "Éloigné",
    relations_enemy: "Ennemi",
    relations_opposite: "Opposé",
    religion: "Religion",
    research_placeholder: "Rechercher par nom",
    sex: "Sexe",
    wound_threshold: "Seuil de blessure",
  },
  guild: {
    single: "Guilde",
  },
  inventory: {
    single: "Inventaire",
  },
  market: {
    single: "Marché",
  },
  pet: {
    single: "Familier & monture",
  },
  race: {
    single: "Race",
    add: "Ajouter une race",
    appearance: "Apparence",
    blood_cross: "Croisé",
    blood_half: "Sang-mêlée",
    blood_percentage: "Pourcentage de Sang",
    blood_pure: "Sang-pur",
    breading_race: "Race de croisement",
    categorie: "Catégorie",
    character: "Caractère",
    create: "Nouvelle race",
    playable: "Jouable",
    plural: "Races",
    primary_race: "Race principale",
    race_placeholder: "Choisissez une race",
    stat1: "Stat 1",
    stat2: "Stat 2",
    type: "Type",
    type_placeholder: "Choisit une famille des sang",
  },
  relation: {
    plural: "Relations",
  },
  stat: {
    agility: "Agilité",
    agility_tooltip:
      "Détermine le niveau d'agilité de votre personnages\net augmente sa forme max.",
    constitution: "Constitution",
    constitution_tooltip:
      "Détermine le niveau de constitution de votre personnage\net augmente ses points de vie max.",
    force: "Force",
    force_tooltip:
      "Détermine le niveau de force de votre personnage\net augmente sa forme max.",
    intelligence: "Intelligence",
    intelligence_tooltip:
      "Détermine le niveau d'intelligence de votre personnage\net augmente son mana max.\nInflue sur les connaissances de votre personnage.",
    knowHow: "Savoir-faire",
    knowHow_tooltip: "Détermine le niveau de savoir-faire de votre personnage.",
    power: "Pouvoir",
    power_tooltip:
      "Détermine le niveau de pouvoir de votre personnage\net augmente son mana max.\nInflue sur les capacités magiques de votre personnage.",
    sociable: "Sociable",
    sociable_tooltip:
      "Détermine le niveau de sociable de votre personnage.\nInflue sur l'image (hors physique) que renvoit votre personnage aux autres.",
    social: "Social",
    social_tooltip:
      "Détermine le niveau de social de votre personnage.\nInflue sur ses capacités à influencer les autres personnages.",
    to_allocate: "Points à répartir",
    too_much_max:
      "Un trop grand nombre de stat actuellement au maximum ({maxPoints})",
    will: "Volonté",
    will_tooltip:
      "Détermine le niveau de volonté de votre personnage.\nInflue sur la perception de votre personnage.",
  },
  technique_spell: {
    plural: "Sorts et Techniques",
    active: "Actif",
    passive: "Passif",
  },
} as const;
