import { Providers } from "./providers";

type Params = Promise<{ locale: string }>;

// export async function generateMetadata({ params }: { params: Params }) {
//   // const { locale } = await params;
//   // console.log(locale);
//   return {
//     title: "Create Next App",
//     description: "Generated by create next app",
//     icon: "my-icon.ico",
//   };
// }

export default async function LocalLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Params;
}) {
  const { locale } = await params;

  return <Providers locale={locale}>{children}</Providers>;
}
